[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unlicense",
    "CC0-1.0",
]
copyleft = "deny"
default = "deny"

[bans]
multiple-versions = "deny"
deny = []
skip = [
    # If any crates require multiple versions, add them here
]
